name: brew bump

on:
  schedule:
    # Runs at 2:47am on Mondays.
    - cron: "47 2 * * 1"
  workflow_dispatch:

jobs:
  autobump:
    runs-on: macos-26
    if: github.repository == 'BD103/homebrew-tap'
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@8f3d1ec8a696b3b9d9a6c3696b6c73033cab69e4 # 2026.08.14.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@8f3d1ec8a696b3b9d9a6c3696b6c73033cab69e4 # 2026.08.14.1
        with:
          username: ${{ (github.event_name == 'workflow_dispatch' && github.actor) || 'BrewTestBot' }}

      - name: Bump casks
        run: brew bump --tap BD103/tap --no-fork --open-pr
